services:
  database:
    ports:
      - 5432:5432

  nats:
    ports:
      - "4222:4222"

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/backend/src:/backend/src
      - ./var/backend:/backend/var/app

  redis:
    ports:
      - "6379:6379"

  generator:
    build:
      context: ./services/generator
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/generator/src:/generator/src
      - ./var/generator:/generator/var/app
