services:
  database:
    restart: unless-stopped

  nats:
    restart: unless-stopped

  backend:
    restart: unless-stopped
    volumes:
      - ./var/backend:/backend/var/app
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.urlshortener.rule=Host(`csmmark.me`)"
      - "traefik.http.routers.urlshortener.entrypoints=websecure"
      - "traefik.http.routers.urlshortener.tls.certresolver=letsencrypt"
      - "traefik.http.services.urlshortener.loadbalancer.server.port=8000"

  redis:
    profiles: [disabled]

  generator:
    restart: unless-stopped
    volumes:
      - ./var/generator:/generator/var/app
    networks:
      - urlshortener
      - shared-network

networks:
  traefik-network:
    external: true
  shared-network:
    external: true
    name: shared-network
