FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

WORKDIR /backend

ENV UV_COMPILE_BYTECODE=0
ENV UV_LINK_MODE=copy
ENV UV_TOOL_BIN_DIR=/usr/local/bin

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

COPY . /backend
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

ENV PATH="/backend/.venv/bin:$PATH"

ENTRYPOINT []

CMD ["hypercorn", "src.main:app", "--bind", "::", "--reload"]
